3 Page sizes added
saurabhdaware/text-to-handwriting pull request #63
Opened 2020-07-04 18:09 UTC by iampratham29

2020-07-05 06:30 UTC, saurabhdaware requested changes
Hi I've added a comment below

2020-07-05 06:30 UTC, saurabhdaware commented on js/PageSize.js
> +    document.getElementById('page-a').style.height = (11 * 400) / 8.5;
Hi I guess you're supposed to add `+ 'px'` at the end to get that value in pixels

2020-07-05 06:32 UTC, saurabhdaware commented on js/PageSize.js
> +    document.getElementById('page-a').style.height = (11 * 400) / 8.5;
oh and page-a is class so you will have to replace `document.getElementById('page-a')` with `document.querySelector('.page-a')`

2020-07-06 09:34 UTC, saurabhdaware requested changes
Oh ok I understood what is missing, so the function pgSize is undefined for the page because it is not included in the HTML. You can copy-paste that function into [js/app.mjs](https://github.com/saurabhdaware/text-to-handwriting/blob/master/js/app.mjs) file and it is supposed to work then

2020-07-06 09:48 UTC, iampratham29 commented
But I had defined it😧

2020-07-06 09:50 UTC, iampratham29 commented
Okay.. I'll do that again

2021-01-29 14:11 UTC, saurabhdaware commented
Closing this since it will have lots of conflicts now 😅

2021-01-29 14:11 UTC, closed without merging